// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHyuSfxxYyMC_Bo0Lwl_0djp0_ToxS_EI',
    appId: '1:80231157243:web:c93d941720aa00a9c04f5e',
    messagingSenderId: '80231157243',
    projectId: 'fluttercourse2-ebaa5',
    authDomain: 'fluttercourse2-ebaa5.firebaseapp.com',
    storageBucket: 'fluttercourse2-ebaa5.appspot.com',
    measurementId: 'G-R7Q6MFVYYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj-3H8dl8eG5Z1hY8gM4nms-dRHcBqYN8',
    appId: '1:80231157243:android:ad43e5bc859e38dbc04f5e',
    messagingSenderId: '80231157243',
    projectId: 'fluttercourse2-ebaa5',
    storageBucket: 'fluttercourse2-ebaa5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1iZ-pXId90mfjJWrgwxDHL1gEA7J3ATw',
    appId: '1:80231157243:ios:f0ec362db7ac0435c04f5e',
    messagingSenderId: '80231157243',
    projectId: 'fluttercourse2-ebaa5',
    storageBucket: 'fluttercourse2-ebaa5.appspot.com',
    androidClientId: '80231157243-n3vekjeg30apr81ouecqsmcp4j47i17p.apps.googleusercontent.com',
    iosClientId: '80231157243-cuphfaer1f6k5atm25gl76hd0p4sukpg.apps.googleusercontent.com',
    iosBundleId: 'com.example.swallow1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1iZ-pXId90mfjJWrgwxDHL1gEA7J3ATw',
    appId: '1:80231157243:ios:857812d725e44b4cc04f5e',
    messagingSenderId: '80231157243',
    projectId: 'fluttercourse2-ebaa5',
    storageBucket: 'fluttercourse2-ebaa5.appspot.com',
    androidClientId: '80231157243-n3vekjeg30apr81ouecqsmcp4j47i17p.apps.googleusercontent.com',
    iosClientId: '80231157243-8s2k6nufe6oqftnjbe5r0m05bm4roi1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.swallow1.RunnerTests',
  );
}
